# config/chewy.yml
# separate environment configs
<% if ENV['chewy'] %>
  test:
    host: 'localhost:9200'
    prefix: 'test'
<% else %>
  test:
    host: 'localhost:9250'
    prefix: 'test'
<% end %>
development:
  host: 'localhost:9200'